Create issue template for bug reporting
TritonSE/ALUM-Mobile-Application pull request #100
Opened 2023-04-23 18:17 UTC by AmanKAggarwal

### Tracking Info
Now that we are almost done, we will be testing things more so might find bugs. It's important to track those bugs as github issues so we never loose track of them. Anyone should feel free to make these issues whenever you see a bug

### Changes

What changes did you make?
- Added an issue template for bugs

### Testing

How did you confirm your changes worked? 
N/A

### Confirmation of Change 
N/A

2023-04-23 18:20 UTC, mrinals108 approved these changes

2023-04-23 18:51 UTC, petabite requested changes

2023-04-23 18:51 UTC, petabite commented on .github/ISSUE_TEMPLATE/bug.md
> +**Describe the probleme**
```suggestion
**Describe the problem**
```
typo?

2023-04-23 20:08 UTC, petabite approved these changes
👌

2023-04-24 18:20 UTC, mrinals108 approved these changes

2023-04-24 21:25 UTC, merged