sessions GET returns an array of sessionIDs not a bunch of session info
TritonSE/ALUM-Mobile-Application pull request #104
Opened 2023-04-27 02:49 UTC by christen03

### Changes

Sessions GET route now returns an array of all sessionIDs instead of an array of sessions with all their info.

### Testing

<img width="996" alt="image" src="https://user-images.githubusercontent.com/99223047/234747213-e307847b-c66d-4e08-9063-fc2daa56c063.png">

2023-04-27 18:34 UTC, AmanKAggarwal approved these changes
LGTM

2023-04-27 19:05 UTC, mrinals108 approved these changes

2023-04-27 21:40 UTC, AmanKAggarwal requested changes
Not merging this rn cauz need to discuss few things to hash-out for v2. No action item needed for this

2023-05-17 01:37 UTC, AmanKAggarwal commented
closing because ALL sessions page does need more info on each session than just an ID for session. Sorry for the wrong call earlier @christen03

2023-05-17 01:37 UTC, closed without merging