Feature/yash/profile view
TritonSE/ALUM-Mobile-Application pull request #69
Opened 2023-03-09 23:53 UTC by YashRavipati1

### Tracking Info

Resolves #50

Make sure your branch name conforms to: `<feature|staging|bugfix|...>/<username>/<3-4 word description separated by dashes>`. Otherwise, please rename your branch and create a new PR.

### Changes

What changes did you make?

Added the visual aspects for the different profile views, including the MVVM architecture

### Testing

How did you confirm your changes worked? 

Previews of the screens

### Confirmation of Change 

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

![image](https://user-images.githubusercontent.com/63521936/224187289-73f2b7e6-b6f8-4fbc-b56d-2b4ec0cc3e09.png)

![image](https://user-images.githubusercontent.com/63521936/224187339-55b6cb90-8578-4dac-b24e-2c7c8ca54c21.png)

![image](https://user-images.githubusercontent.com/63521936/224187386-8c9ba58a-8e8d-4372-bb60-3b39803d38d5.png)

![image](https://user-images.githubusercontent.com/63521936/224187458-719d35a1-9d46-4a05-b835-dcd518de93e6.png)

2023-03-16 16:27 UTC, wllmwu requested changes
Good work, I've made some suggestions for refactoring this code to make it cleaner, more reusable, and easier to maintain in the future.

2023-03-16 16:39 UTC, wllmwu commented on ALUM/ALUM/Views/ProfileViews/MenteeProfileMentorView.swift
> +                    }
Also, make sure to test this with long strings that wrap onto multiple lines.

2023-04-05 08:26 UTC, YashRavipati1 commented on ALUM/ALUM/Components/MenteeCard.swift
> +                    Rectangle()                .frame(width: 107, height: 75.94)
Most of the decimal values were straight from Figma, but I changed them to be more generic.

2023-04-05 08:34 UTC, YashRavipati1 commented on ALUM/ALUM/Services/APIService.swift
> +        }
Handled in PR #60

2023-04-05 08:48 UTC, YashRavipati1 commented on ALUM/ALUM/Views/ProfileViews/MenteeProfileMentorView.swift
> +                    }
Edited to remove unnecessary HStacks. Already tested with longer strings that wrap.

2023-04-05 08:52 UTC, YashRavipati1 commented on ALUM/ALUM/Views/ProfileViews/MenteeProfileMentorView.swift
> +        GeometryReader { grr in
There are actually a number of changes in addition to the calendly button. The buttons at the top of the view, the why're you paired section (which hasn't been added yet but is a part of the view), profile card(s), etc. are also differences between the views when a different user is viewing the profile. Due to these numerous differences I believe that separating the views would be better for ease of use/readability when connecting the navigation of the app. However, if you still believe that I should merge the views I can make that change.

2023-04-05 08:53 UTC, YashRavipati1 commented on backend/src/config.ts
> +  path: "/Users/yashravipati/Documents/GitHub/ALUM-Mobile-Application/backend/env",
Reverted

2023-04-07 21:49 UTC, AmanKAggarwal requested changes
Great work with the layout! Few changes needed before we can merge this - 
1. Possibly merge the redundant views so that we don't have two different views (one for a mentor viewing vs mentee viewing)
2. Reduce reused code with the use of components
3. Try to remove the hardcoded pixel values as much as possible. Let's chat about this a bit cauz I wanna see the benefits of using the pixels as well if you are aware.  
       - You can use Spacers, add paddings around your Textboxes etc.
       - Doing these things makes it more resizable and easy to change in the future.

2023-04-12 04:21 UTC, AmanKAggarwal reviewed
Great stuff with the PR! Just couple of minor things - 
1. Delete `NavigationComponent` because it is unused it seems. Correct me if I am wrong
2. Update the colors as per the current figma

2023-04-12 04:58 UTC, sidhantrohatgi approved these changes

2023-04-13 14:55 UTC, AmanKAggarwal approved these changes
LGTM. Just the one change to delete the unused component

2023-04-13 21:36 UTC, YashRavipati1 commented on ALUM/ALUM/Components/NavigationComponent.swift
> +//
This component is actually used in both menteeprofileview and mentor profileview for when its not the user viewing their own profile.

2023-04-14 04:49 UTC, AmanKAggarwal approved these changes
still looks good

2023-04-19 16:56 UTC, closed without merging